on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: X100
        uses: actions/checkout@v4

      - name: X101
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "sbt"

      - name: X102
        run: sbt test
